# Generated by Django 2.1.7 on 2019-03-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=120)),
                ('Teacher', models.TextField()),
                ('day_of_week', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], default='Mon', max_length=3)),
                ('Time_start', models.TimeField()),
                ('Time_end', models.TimeField()),
                ('Classes', models.CharField(max_length=10)),
            ],
        ),
    ]
