# Generated by Django 2.1.7 on 2019-03-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='Time_end',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='Time_start',
        ),
        migrations.AddField(
            model_name='articles',
            name='time_of_day',
            field=models.CharField(choices=[('1', 'Первая'), ('2', 'Вторая'), ('3', 'Третья'), ('4', 'Четвертая'), ('5', 'Пятая'), ('6', 'Шестая')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='articles',
            name='Teacher',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='articles',
            name='day_of_week',
            field=models.CharField(choices=[('Mon', 'Понедельник'), ('Tue', 'Вторник'), ('Wed', 'Среда'), ('Thu', 'Четверг'), ('Fri', 'Пятница'), ('Sat', 'Суббота')], default='Mon', max_length=3),
        ),
    ]
