# Generated by Django 2.1.7 on 2019-03-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_auto_20190306_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='type_of_week',
            field=models.CharField(choices=[('Четная', 'Четная'), ('Нечетная', 'Нечетная')], default='Четная', max_length=20),
        ),
    ]
