# Generated by Django 2.1.7 on 2019-03-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_articles_type_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='day_of_week',
            field=models.CharField(choices=[('1Понедельник', 'Понедельник'), ('2Вторник', 'Вторник'), ('3Среда', 'Среда'), ('4Четверг', 'Четверг'), ('5Пятница', 'Пятница'), ('6Суббота', 'Суббота')], default='1Понедельник', max_length=20),
        ),
    ]
