# Generated by Django 2.1.7 on 2019-03-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_auto_20190306_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='type_of_week',
            field=models.CharField(choices=[('Четная', 'Четная'), ('Нечетная', 'Нечетная'), ('Еженедельно', 'Еженедельно')], default='Еженедельно', max_length=20),
        ),
    ]
