# Generated by Django 2.1.7 on 2019-03-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_auto_20190308_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='Group_user',
            field=models.CharField(default='', max_length=15),
        ),
    ]
